import {
    BandhuWeb,
    D2K_Web,
    HacknicheWeb,
    Law4AllWeb,
    LocWeb,
    Portfolio_Web,
    VaniVikasWeb,
    VerityFinanceWeb,
} from "@/public";

export const projectsData = [
    {
        id: 1,
        title: "🔐 Decentralized Document Vault",
        year: "2025",
        description:
            "A secure, blockchain-powered platform for storing, accessing, and verifying sensitive documents. By leveraging decentralized storage and smart contracts, it ensures data integrity, privacy, and tamper-proof access control—empowering users with full ownership and transparency over their digital records.",
        image: VaniVikasWeb,
        isWinner: true,
        hackathon: "IEEE Pune 2025",
        technologies: [
            "Smart Contracts",
            "HTML",
            "CSS",
            "JavaScript",
            "EJS",
            "Node.js",
            "OpenAI",
            "Express.js",
            "MongoDB",
            "TLS Handshake",
            "Git & GitHub",
            "FastAPI",
            "Postman",
        ],
        link: "https://blockchain-image-frontend.vercel.app/",
        madeAt: "IEEE Pune 2025",
    },
    {
        id: 2,
        title: "E-Book-Store - BookHaven",
        year: "2024-2025",
        description:
            "BookHaven is a dynamic PHP-based e-commerce platform designed specifically for book lovers. This web application offers a seamless book shopping experience with features like user authentication, shopping cart functionality, wishlist management, and an intuitive admin panel for inventory control. Built with PHP, MySQL, and modern web technologies",
        image: BandhuWeb,
        isWinner: true,
        hackathon: "Class Project 2024-2025",
        technologies: [
            "PHP 8.1.2",
            "MySQL",
            "CSS3",
            "HTML5",
            "JavaScript",
            "Web browser",
            "React Native",
            "XAMPP Server",
        ],
        link: "https://bookstore-c14.infinityfreeapp.com/?i=1",
        madeAt: "Class Project 2024-2025",
    },
    {
        id: 3,
        title: "Multi-Game Interface",
        year: "2025",
        description:
            "Welcome to Multi-Game Interface, a web-based platform that consolidates multiple games and applications onto a single page for easy access. Each game is hosted separately and linked through this interface. This project aims to provide a simple and engaging experience for users to enjoy various games in one place.",
        image: VerityFinanceWeb,
        isWinner: false,
        hackathon: "Datazen 2025",
        technologies: [
            "HTML5",
            "CSS3",
            "Hosted Links",
            "JavaScript"
        ],
        link: "https://github.com/sameer240704/verity-finance-datazen",
        madeAt: "Datazen 2025",
    },
    {
        id: 4,
        title: "Better World - CSR Management",
        year: "2025",
        description:
            "Vani Vikas is a comprehensive digital platform which aims to digitize and manage the entire speech language therapy process from patient registration to therapy completion. A website and an application together make the entire speech therapy process a seamless one.",
        image: LocWeb,
        isWinner: true,
        hackathon: "Lines of Code 7.0",
        technologies: [
            "Next.js",
            "Python",
            "TailwindCSS",
            "ShadCN",
            "Gemini 2.0 Pro",
            "Ollama3",
            "Azure",
            "Flutter",
            "MongoDB",
            "Three.js",
            "Mixtral-8x7b",
            "Mapbox",
            "Groq API",
        ],
        link: "https://youtu.be/0kGHDOfh8jk",
        madeAt: "Lines of Code 7.0",
    },
    {
        id: 5,
        title: "ShopMart - AI-driven shopping platform",
        year: "2025",
        description:
            "ShopMart is a mobile-compatible e-commerce platform with an AI-powered recommendation system, personalized discounts, and a loyalty program. It features real-time analytics, visual search, natural language queries, and multi-role dashboards to enhance user experience and drive sales.",
        image: HacknicheWeb,
        isWinner: false,
        hackathon: "Hackniche 3.0",
        technologies: [
            "Next.js",
            "Python",
            "Ollama3",
            "TailwindCSS",
            "ShadCN",
            "Gemini 2.0 Pro",
            "Azure",
            "MongoDB",
            "Three.js",
            "Selenium",
            "Neo4j AuraDB",
            "Unity Engine",
            "Groq API",
        ],
        link: "https://github.com/sameer240704/bestiesofsyntax_hackniche3",
        madeAt: "Hackniche 3.0",
    },
    {
        id: 6,
        title: "Law4All - AI-powered free legal guidance assistant",
        year: "2025",
        description:
            "Law4All is an AI-powered legal aid advisor to help low-income individuals navigate disputes like evictions or wage theft. By analyzing case details and legal databases, it provides step-by-step guidance, risk predictions, and document templates—accessible via a free multilingual app or chatbot, empowering users to secure fair outcomes.",
        image: Law4AllWeb,
        isWinner: true,
        hackathon: "Hack2Infinity",
        technologies: [
            "Next.js",
            "Python",
            "Ollama3",
            "TailwindCSS",
            "ShadCN",
            "Gemini 2.0 Pro",
            "React Native",
            "Azure",
            "MongoDB",
            "Three.js",
            "Neo4j AuraDB",
            "Groq API",
            "LangChain",
            "Streamlit",
            "Eleven Labs",
            "Twilio",
            "Meta AI",
        ],
        link: "https://law4all-bournvita-smugglers.vercel.app/en",
        madeAt: "Hack2Infinity",
    },
    {
        id: 7,
        title: "Fin360 - AI-Powered Financial Statement Analysis",
        year: "2025",
        description:
            "AI-driven platform automating financial statement analysis for investment firms. Extracts insights from balance sheets, income statements, and notes with NLP, detects anomalies, benchmarks against peers, and generates predictive reports—transforming manual due diligence into real-time decision intelligence.",
        image: D2K_Web,
        isWinner: true,
        hackathon: "Data 2 Knowledge 3.0",
        technologies: [
            "Next.js",
            "Python",
            "Mistral OCR",
            "Ollama3",
            "TailwindCSS",
            "ShadCN",
            "Gemini API",
            "Faiss Embeddings",
            "MongoDB",
            "Three.js",
            "Neo4j AuraDB",
            "Groq API",
            "LangChain",
            "Streamlit",
        ],
        link: "https://fin360-bournvita-smugglers.vercel.app/en",
        madeAt: "Data 2 Knowledge 3.0",
    },
    {
        id: 8,
        title: "Cosmos AI: AI-driven Procedural Content Generation and Dynamic Difficulty Adjustment",
        year: "2024",
        description: "",
        image: D2K_Web,
        isWinner: false,
        technologies: [
            "Python",
            "DCGAN",
            "OpenCV",
            "RNN",
            "LSTM",
            "React.js",
            "Typescript",
            "ShadCN",
            "TailwindCSS",
        ],
        link: "",
        madeAt: "Personal Project",
    },
    {
        id: 9,
        title: "Personal Portfolio",
        year: "2025",
        description: "",
        image: Portfolio_Web,
        isWinner: false,
        technologies: [
            "Next.js",
            "TailwindCSS",
            "ShadCN",
        ],
        link: "https://sameer-gupta.vercel.app/",
        madeAt: "Personal Project"
    }
];
